# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "molecule-dnsdist" do |test|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    test.vm.box = "bento/ubuntu-16.04"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    test.vm.network "private_network", type: "dhcp"

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    test.vm.provider "virtualbox" do |vb|
      # Customize the VM name
      vb.name = "molecule-dnsdist"

      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end
    
    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
    # test.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install -y apache2
    # SHELL
  end

end
