FROM {{ item.image }}

# Tell systemd that we're running inside a Docker container.
ENV container docker

# Make sure systemd is fully installed in the system.
RUN apt-get update \
  && apt-get install -y systemd \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Don't start the optional systemd services. 
RUN cd /lib/systemd/system/sysinit.target.wants/; ls | grep -v systemd-tmpfiles-setup | xargs rm -f $1 \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*; \
rm -f /lib/systemd/system/plymouth*; \
rm -f /lib/systemd/system/systemd-update-utmp*;

RUN systemctl set-default multi-user.target

VOLUME [ "/sys/fs/cgroup" ]
CMD [ "/sbin/init" ]

# Make sure all the Ansible dependencies are there.
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y python sudo bash ca-certificates gnupg \
  && apt-get clean
