---

scenario:
  name: dnsdist-17

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: oraclelinux-7
    image: oraclelinux:7
    dockerfile_tpl: centos-systemd

  - name: oraclelinux-8
    image: oraclelinux:8
    dockerfile_tpl: centos-systemd

  - name: oraclelinux-9
    image: oraclelinux:9
    dockerfile_tpl: centos-systemd

  - name: ubuntu-2004
    image: ubuntu:20.04
    dockerfile_tpl: ubuntu-systemd

  - name: ubuntu-2204
    image: ubuntu:22.04
    dockerfile_tpl: ubuntu-systemd

  - name: debian-10
    image: debian:10
    dockerfile_tpl: debian-systemd

  - name: debian-11
    image: debian:11
    dockerfile_tpl: debian-python3

  - name: rockylinux-8
    image: rockylinux:8
    dockerfile_tpl: centos-systemd

  - name: almalinux-8
    image: almalinux:8
    dockerfile_tpl: centos-systemd

  - name: rockylinux-9
    image: rockylinux:9.0
    dockerfile_tpl: centos-systemd

  - name: almalinux-9
    image: almalinux:9
    dockerfile_tpl: centos-systemd

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  inventory:
    links:
      host_vars: ../resources/host_vars/
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml

lint: yamllint vars tasks defaults meta

verifier:
  name: testinfra
  options:
    vvv: True
  directory: ../resources/tests/all
  additional_files_or_dirs:
    # path relative to 'directory'
    - ../repo-17/
