---

- name: restart dnsdist
  service:
    name: dnsdist
    state: restarted
    sleep: 1                          # the sleep is needed to make sure the service has been
  when: not dnsdist_disable_handlers  # correctly started after being stopped during restarts

- name: reload systemd and restart dnsdist
  command: systemctl daemon-reload
  notify: restart dnsdist
  when: not dnsdist_disable_handlers
