---
# the sleep in the restart dnsdist handler
# is needed to make sure the service has been
# correctly stopped before being started again during restarts

- name: Reload systemd and restart dnsdist
  ansible.builtin.systemd:
    daemon_reload: true
  notify: restart dnsdist
  when: not dnsdist_disable_handlers

- name: Restart dnsdist
  ansible.builtin.service:
    name: dnsdist
    state: restarted
    sleep: 1
  when: dnsdist_service_state != 'stopped' and not dnsdist_disable_handlers

- name: Update the APT cache
  ansible.builtin.apt:
    update_cache: true
