---

scenario:
  name: dnsdist-16

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: centos-7
    image: centos:7
    dockerfile_tpl: centos-systemd

  - name: centos-8
    image: quay.io/centos/centos:stream8
    dockerfile_tpl: centos-systemd

  - name: ubuntu-1804
    image: ubuntu:18.04
    dockerfile_tpl: debian-systemd

  - name: ubuntu-2004
    image: ubuntu:20.04
    dockerfile_tpl: debian-systemd

  - name: debian-10
    image: debian:10
    dockerfile_tpl: debian-systemd

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  inventory:
    links:
      host_vars: ../resources/host_vars/
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml
  
lint: yamllint vars tasks defaults meta

verifier:
  name: testinfra
  options:
    vvv: True
  directory: ../resources/tests/all
  additional_files_or_dirs:
    # path relative to 'directory'
    - ../repo-16/
